; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
description = Astra

[env]
lib_deps = 
	https://github.com/Terrapin-Rocket-Team/Astra.git#dev
lib_ignore = NativeTestMocks
lib_compat_mode = strict
build_flags = 
	-Wno-unknown-pragmas
	-std=gnu++17
build_src_filter = +<*> +<../examples/Avionics/**>
extra_scripts = pre:get_version.py

[env:teensy41]
platform = teensy
framework = arduino
board = teensy41

[env:stm]
platform = ststm32
framework = arduino
board = nucleo_h753zi
build_flags = 

[env:esp32]
platform = espressif32
framework = arduino
board = esp32-s3-devkitm-1
build_unflags = -std=gnu++11

[env:native]
platform = native
lib_deps =
	https://github.com/Terrapin-Rocket-Team/Astra.git#minor-cleanup
	throwtheswitch/Unity@^2.6.0
lib_ignore =
lib_compat_mode = off
test_build_src = yes
build_flags =
	-Wno-unknown-pragmas
	-std=c++17
	-DPIO_UNIT_TESTING
	-DNATIVE=1
	-DUNITY_INCLUDE_DOUBLE
	-I.pio/libdeps/native/TRT-Astra/src
	-I.pio/libdeps/native/Unity/src
	-Ilib/NativeTestMocks
test_framework = unity
build_src_filter =
	+<*>
	-<../examples/>
	-<AstraRocket.cpp>
	+<../.pio/libdeps/native/TRT-Astra/src/*>
	-<../.pio/libdeps/native/TRT-Astra/src/Sensors/**>
	+<../.pio/libdeps/native/TRT-Astra/src/Sensors/Baro/Barometer.cpp>
	+<../.pio/libdeps/native/TRT-Astra/src/Sensors/Baro/MockBarometer.cpp>
	+<../.pio/libdeps/native/TRT-Astra/src/Sensors/GPS/GPS.cpp>
	+<../.pio/libdeps/native/TRT-Astra/src/Sensors/GPS/MockGPS.cpp>
	+<../.pio/libdeps/native/TRT-Astra/src/Sensors/IMU/IMU.cpp>
	+<../.pio/libdeps/native/TRT-Astra/src/Sensors/IMU/MockIMU.cpp>
	+<../.pio/libdeps/native/TRT-Astra/src/Sensors/SerialReader.cpp>
	-<../.pio/libdeps/native/TRT-Astra/src/RecordData/Logging/LoggingBackend/LoggingBackendLittleFS.cpp>
	-<../.pio/libdeps/native/TRT-Astra/src/RecordData/Logging/LoggingBackend/LoggingBackendSdFat.cpp>
	-<../.pio/libdeps/native/TRT-Astra/src/Radio/**>
lib_ldf_mode = chain+
lib_extra_dirs =
	.pio/libdeps/native/TRT-Astra
	.pio/libdeps/native/Unity
	lib
debug_build_flags = -g -O0 -fstack-protector-all